### ISSUE TITLE
상점 핀 표시 (메인 페이지)

### ISSUE THREAD

**Issue by Invidam** [BCSDLab/JJBAKSA_BACK_END#88]
## Description

메인 페이지 지도 위 상점 핀(이름과 이미지)을 표시
## Task List

- [x] 가까운 음식점
- [x] 친구 음식점, 북마크 음식점
- ~~현 위치의 상점 목록 검색~~

## Remark

- 이미지는 사장님이 올린 이미지로 함.
- 가까운 음식점, 현 위치에서 검색 중 구현이 어려운 내용은 1차 배포에서 제외함.

**Comment by Invidam** [comment]
@Yoojkim 가까운 음식점, 현 위치에서 검색 중 (다른 내용도 괜찮) 구현이 어려운 내용이 있으면 코멘트 남겨주세요!

**Comment by Yoojkim** [comment]
가까운 음식점, 북마크 음식점은 구현 완료하였고
친구 음식점 같은 경우에는 친구가 리뷰 작성한 음식점에 한하는 거라 현재 리뷰쪽에 변경된 상점 로직이 반영되지 않아서 이는 아직 구현되지 않았습니다. (코드에서도 공란으로 비워놓고 테스트코드도 작성 안 되어있습니다~) 

추가적으로, 현 위치의 상점 목록 검색이 어떤 부분 말씀하시는 건지 여쭤봐도 될까요?

**Comment by Invidam** [comment]
피그마의 해당 부분입니다!
![image](https://github.com/BCSDLab/JJBAKSA_BACK_END/assets/71889359/e44a3854-73ce-4be4-a8b2-3ad82e60b333)

아마 메인페이지에서, 근처에 있는 상점 목록을 띄워주는 것 화면 같아요.

#91 로 옮겼어요!
